<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>2ab3a0b4-c2b6-4f21-9173-3309afbffb8a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\corsair-tide-new.Server\corsair-tide-new.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.3" />
  </ItemGroup>
</Project>
